position_fixes = {
    'G': 'Guard',
    'F': 'Forward',
    'C': 'Center',
    'M': 'Midfielder',
    'D': 'Defender',
    'GK': 'Goalkeeper',
    'M/F': 'Midfielder / Forward',
    'F/M': 'Forward / Midfielder',
    'M/D': 'Midfielder / Defender',
    'D/M': 'Defender / Midfielder'
}

year_fixes = {
    'Fr.': 'Freshman',
    'So.': 'Sophomore',
    'Jr.': 'Junior',
    'Sr.': 'Senior',
    'Gr.': 'Graduate Student',
    'R-Fr.': 'Redshirt Freshman',
    'R-So.': 'Redshirt Sophomore',
    'R-Jr.': 'Redshirt Junior',
    'R-Sr.': 'Redshirt Senior'
}

state_fixes = {
    'Ala.': 'Alabama',
    'Ariz.': 'Arizona',
    'Ark.': 'Arkansas',
    'Calif.': 'California',
    'Colo.': 'Colorado',
    'Conn.': 'Connecticut',
    'Del.': 'Delaware',
    'Fla.': 'Florida',
    'Fla': 'Florida',
    'Ga.': 'Georgia',
    'Ill.': 'Illinois',
    'Ind.': 'Indiana',
    'Kan.': 'Kansas',
    'Ky.': 'Kentucky',
    'La.': 'Louisiana',
    'Md.': 'Maryland',
    'Mass.': 'Massachusetts',
    'Mich.': 'Michigan',
    'Minn.': 'Minnesota',
    'Miss.': 'Mississippi',
    'Mo.': 'Missouri',
    'Mont.': 'Montana',
    'Neb.': 'Nebraska',
    'Nev.': 'Nevada',
    'N.H.': 'New Hampshire',
    'N.J.': 'New Jersey',
    'N.M.': 'New Mexico',
    'N.Y.': 'New York',
    'N.C.': 'North Carolina',
    'N.D.': 'North Dakota',
    'Okla.': 'Oklahoma',
    'Ore.': 'Oregon',
    'Pa.': 'Pennsylvania',
    'R.I.': 'Rhode Island',
    'S.C.': 'South Carolina',
    'S.D.': 'South Dakota',
    'Tenn.': 'Tennessee',
    'Vt.': 'Vermont',
    'Va.': 'Virginia',
    'Wash.': 'Washington',
    'W.Va.': 'West Virginia',
    'Wis.': 'Wisconsin',
    'Wyo.': 'Wyoming'
}
